# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy the project files into the container
COPY . .

# Install dependencies. We install mcp with cli extras and httpx dependency.
RUN pip install --no-cache-dir "mcp[cli]>=1.4.1" httpx

# Expose any ports if necessary (not required for stdio transport)

# Command to run the MCP server
CMD ["python", "main.py"]
