# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install system dependencies if required
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir "mcp[cli]>=1.4.1" httpx

# Expose port if needed (not required for stdio transport)

# Run the MCP server using the main entry point
CMD ["python", "main.py"]
